"""add published_date column

Revision ID: 733a1f7b776f
Revises: 
Create Date: 2026-07-11 14:33:13.891913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733a1f7b776f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('published_date', sa.Date(), nullable=False))
    op.drop_column('books', 'published_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('published_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('books', 'published_date')
    # ### end Alembic commands ###
