"""add booktag link table, drop book_uid from tags and change genre col to language

Revision ID: 93122f866fac
Revises: 43f0816d4ab2
Create Date: 2026-10-01 20:53:30.869566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93122f866fac'
down_revision: Union[str, None] = '43f0816d4ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booktag',
    sa.Column('book_uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tag_uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['book_uid'], ['books.uid'], ),
    sa.ForeignKeyConstraint(['tag_uid'], ['tags.uid'], ),
    sa.PrimaryKeyConstraint('book_uid', 'tag_uid')
    )
    op.alter_column('books', 'genre', new_column_name='language')
    op.drop_constraint('tags_book_uid_fkey', 'tags', type_='foreignkey')
    op.drop_column('tags', 'book_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('book_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('tags_book_uid_fkey', 'tags', 'books', ['book_uid'], ['uid'])
    op.alter_column('books', 'language', new_column_name='genre')
    op.drop_table('booktag')
    # ### end Alembic commands ###
